# Generated by Django 4.2.9 on 2024-05-20 11:38

import crawl.models.movie_photo
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="آیا حذف شده است؟"
                    ),
                ),
                ("title", models.CharField(max_length=256, verbose_name="عنوان فیلم")),
                ("story_line", models.TextField(verbose_name="توضیحات")),
                (
                    "rating_value",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="رنکینگ",
                    ),
                ),
                (
                    "rating_count",
                    models.PositiveBigIntegerField(
                        verbose_name="تعداد نمره\u200cدهندگان"
                    ),
                ),
            ],
            options={
                "verbose_name": "",
                "verbose_name_plural": "",
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="MovieCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="آیا حذف شده است؟"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=32, unique=True)),
                (
                    "crawl_status",
                    models.CharField(
                        choices=[
                            ("not crawled", "کرال نشده"),
                            ("crawl failure", "کرال با شکست"),
                            ("wrong code", "کد اشتباه"),
                            ("craw successfully", "کرال با موفقیت"),
                        ],
                        db_index=True,
                        default="not crawled",
                        max_length=256,
                    ),
                ),
                (
                    "last_crawl",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان آخرین کرال"
                    ),
                ),
            ],
            options={
                "verbose_name": "",
                "verbose_name_plural": "",
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="MovieSimilarity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_similar_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similar_to",
                        to="crawl.moviecode",
                        verbose_name="فیلم مربوطه",
                    ),
                ),
                (
                    "the_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="more_like_this",
                        to="crawl.moviecode",
                        verbose_name="فیلم مربوطه",
                    ),
                ),
            ],
            options={
                "verbose_name": "",
                "verbose_name_plural": "",
            },
        ),
        migrations.CreateModel(
            name="MoviePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=crawl.models.movie_photo.movie_photo_upload_to,
                        verbose_name="فایل تصویر",
                    ),
                ),
                (
                    "downloaded_url",
                    models.URLField(max_length=1048, verbose_name="آدرس دانلود شده"),
                ),
                ("photo_code", models.CharField(max_length=32, verbose_name="کد عکس")),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="crawl.movie",
                        verbose_name="فیلم مربوطه",
                    ),
                ),
            ],
            options={
                "verbose_name": "",
                "verbose_name_plural": "",
            },
        ),
        migrations.AddField(
            model_name="movie",
            name="movie_code",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="crawled_movie",
                to="crawl.moviecode",
                verbose_name="کد IMDB",
            ),
        ),
    ]
